# version: "3.8"

services:
  # Laravel backend
  laravel_app:
    build: ./docker/php
    container_name: portfolio_php
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:latest
    container_name: portfolio_nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - app-network

  # MySQL
  db:
    image: mysql:8
    container_name: portfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - "3308:3306"
    volumes:
      - portfolio_db_data:/var/lib/mysql
    networks:
      - app-network

  # React
  react:
    image: node:20
    container_name: portfolio_frontend
    working_dir: /app
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    networks:
      - app-network

volumes:
  portfolio_db_data:

networks:
  app-network:
    driver: bridge